from typing import Optional

class VirgilKYC:
    def __init__(self, country_name: str, country_code: Optional[str] = None,
                 code_lookup: Optional[bool] = False) -> None:
        self.country_name = country_name
        self.country_code = country_code
        self.code_lookup = code_lookup

    def get_subaccount_entity_form_field_xpath_map(self) -> dict[str, str]:
        country_name = self.country_name
        code_lookup = self.code_lookup
        country_code = self.country_code
        countries_data = [
            {"name": "Australia",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Brazil",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Canada",
             "form_fields": {
                 "prefix": '//*[@id="FieldSections_0__InputFields_0__StandardInput_Value"]',
                 "first_name": '//*[@id="FieldSections_0__InputFields_1__StandardInput_Value"]',
                 "first_initial": '//*[@id="FieldSections_0__InputFields_2__StandardInput_Value"]',
                 "middle_name": '//*[@id="FieldSections_0__InputFields_3__StandardInput_Value"]',
                 "middle_initial": '//*[@id="FieldSections_0__InputFields_4__StandardInput_Value"]',
                 "last_name": '//*[@id="FieldSections_0__InputFields_5__StandardInput_Value"]',
                 "date_of_birth_day": '//*[@id="FieldSections_1__InputFields_0__FieldSetInput_Inputs_0__Value"]',
                 "date_of_birth_month": '//*[@id="FieldSections_1__InputFields_0__FieldSetInput_Inputs_1__Value"]',
                 "date_of_birth_year": '//*[@id="FieldSections_1__InputFields_0__FieldSetInput_Inputs_2__Value"]',
                 "address_1": '//*[@id="FieldSections_2__InputFields_0__StandardInput_Value"]',
                 "unit_number": '//*[@id="FieldSections_2__InputFields_1__StandardInput_Value"]',
                 "civic_number": '//*[@id="FieldSections_2__InputFields_2__StandardInput_Value"]',
                 "street_name": '//*[@id="FieldSections_2__InputFields_3__StandardInput_Value"]',
                 "street_type": '//*[@id="FieldSections_2__InputFields_4__StandardInput_Value"]',
                 "municipality": '//*[@id="FieldSections_2__InputFields_5__StandardInput_Value"]',
                 "province": '//*[@id="FieldSections_2__InputFields_6__DropDownInput_Value"]',
                 "postal_code": '//*[@id="FieldSections_2__InputFields_7__StandardInput_Value"]',
                 "last_update_year": '//*[@id="FieldSections_3__InputFields_0__StandardInput_Value"]',
                 "last_update_month": '//*[@id="FieldSections_3__InputFields_1__StandardInput_Value"]',
                 "last_update_day": '//*[@id="FieldSections_3__InputFields_2__StandardInput_Value"]',
                 "cell_number": '//*[@id="FieldSections_4__InputFields_0__StandardInput_Value"]',
                 "telephone_2": '//*[@id="FieldSections_4__InputFields_1__StandardInput_Value"]',
                 "email_address": '//*[@id="FieldSections_4__InputFields_2__StandardInput_Value"]',
                 "social_insurance_number": '//*[@id="FieldSections_4__InputFields_3__StandardInput_Value"]',
                 "address_association": '//*[@id="FieldSections_4__InputFields_4__StandardInput_Value"]',
                 "phone_type": '//*[@id="FieldSections_4__InputFields_5__StandardInput_Value"]',
                 "risk_level": '//*[@id="FieldSections_4__InputFields_6__StandardInput_Value"]',
                 "risk_description": '//*[@id="FieldSections_4__InputFields_7__StandardInput_Value"]',
                 "mobile_sim_swap_date": '//*[@id="FieldSections_4__InputFields_8__StandardInput_Value"]',
                 "field_used": '//*[@id="FieldSections_4__InputFields_9__StandardInput_Value"]',
                 "operator": '//*[@id="FieldSections_4__InputFields_10__StandardInput_Value"]',
                 "phone_account_type": '//*[@id="FieldSections_4__InputFields_11__StandardInput_Value"]',
                 "phone_account_user": '//*[@id="FieldSections_4__InputFields_12__StandardInput_Value"]',
                 "phone_contract_status": '//*[@id="FieldSections_4__InputFields_13__StandardInput_Value"]',
                 "phone_contract_type": '//*[@id="FieldSections_4__InputFields_14__StandardInput_Value"]',
                 "aml_assist_and_mobile_dual_process":
                     '//*[@id="FieldSections_4__InputFields_15__StandardInput_Value"]',
                 "aml_assist_credit_file_and_mobile_dual_process":
                     '//*[@id="FieldSections_4__InputFields_16__StandardInput_Value"]',
                 "canada_six_month_residency":
                     '//*[@id="FieldSections_4__InputFields_17__StandardInput_Value"]',
                 "fraud_flag": '//*[@id="FieldSections_4__InputFields_18__DropDownInput_Value"]',
                 "three_year_credit": '//*[@id="FieldSections_4__InputFields_19__StandardInput_Value"]',
                 "warning": '//*[@id="FieldSections_4__InputFields_20__StandardInput_Value"]',
                 "consumer_credit": '//*[@id="FieldSections_4__InputFields_21__StandardInput_Value"]',
                 "fraud_message": '//*[@id="FieldSections_4__InputFields_22__DropDownInput_Values"]',
                 "is_deceased": '//*[@id="FieldSections_4__InputFields_23__DropDownInput_Value"]',
                 "six_month_single_source": '//*[@id="FieldSections_4__InputFields_24__StandardInput_Value"]',
                 "telephone": '//*[@id="FieldSections_4__InputFields_25__StandardInput_Value"]'
             }},
            {"name": "China",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Hong Kong",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "New Zealand",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Italy",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Ireland",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Japan",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Nigeria",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Taiwan",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "United Kingdom",
             "form_fields": {
                 "first_name": "xpath",
                 "first_initial": "xpath",
                 "middle_name": "xpath",
                 "middle_initial": "xpath",
                 "last_name": "xpath",
                 "business_name": "xpath",
                 "tradestyle_name": "xpath",
                 "date_of_birth_day": "xpath",
                 "date_of_birth_month": "xpath",
                 "date_of_birth_year": "xpath",
                 "address_1": "xpath",
                 "unit_number": "xpath",
                 "building_number": "xpath",
                 "house_number": "xpath",
                 "building_name": "xpath",
                 "street_name": "xpath",
                 "street_type": "xpath",
                 "city": "xpath",
                 "suburb": "xpath",
                 "county": "xpath",
                 "state": "xpath",
                 "postal_code": "xpath",
                 "second_unit_number": "xpath",
                 "second_street_name": "xpath",
                 "second_street_type": "xpath",
                 "second_suburb": "xpath",
                 "second_postal_code": "xpath",
                 "second_state": "xpath",
                 "business_registration_number": "xpath",
                 "cell_number": "xpath",
                 "email_address": "xpath",
                 "telephone_2": "xpath",
                 "jurisdiction_of_incorporation": "xpath",
                 "duns_number": "xpath",
                 "second_address_1": "xpath",
                 "second_city": "xpath",
                 "second_building_name": "xpath",
                 "second_building_number": "xpath",
                 "tax_id_number": "xpath",
                 "enhanced_profile": "xpath",
                 "business_risk_valies": "xpath",
                 "entities": "xpath",
                 "second_county": "xpath",
                 "people_of_significant_control": "xpath",
                 "annual_accounts": "xpath",
                 "article_of_association": "xpath",
                 "annual_report": "xpath",
                 "capital_document": "xpath",
                 "liquidation_document": "xpath",
                 "mortgage_document": "xpath",
                 "watchlist_data": "xpath",
                 "watchlist_state": "xpath",
                 "watchlist_hit_details": "xpath",
                 "is_decesased": "xpath",
                 "field_used": "xpath",
                 "address_association": "xpath",
                 "phone_type": "xpath",
                 "risk_level": "xpath",
                 "risk_description": "xpath",
                 "mobile_sim_swap_date": "xpath",
                 "operator": "xpath",
                 "business_status": "xpath",
                 "original_business_status": "xpath",
                 "standardized_registration_numbers": "xpath",
                 "standardized_locations": "xpath",
                 "standardized_metadata": "xpath",
                 "basic_product_called": "xpath",
                 "basic_product_returned": "xpath",
                 "enhanced_product_called": "xpath",
                 "enhanced_product_returned": "xpath",
                 "input_business_name_translated": "xpath",
                 "returned_business_name_translated": "xpath",
                 "returned_business_name_transliterated": "xpath",
                 "entities_product_called": "xpath",
                 "entities_product_returned": "xpath",
                 "warning": "xpath",
                 "standardized_business_names": "xpath",
                 "respect_enhanced": "xpath",
                 "business_status_details": "xpath",
                 "standardized_communication": "xpath",
                 "vendor_transactional_references": "xpath",
                 "business_legal_form": "xpath",
                 "original_business_legal_form": "xpath",
                 "year_of_incorporation": "xpath",
                 "month_of_incorporation": "xpath",
                 "day_of_incorporation": "xpath",
                 "standardized_share_capitals": "xpath",
                 "standardized_industries": "xpath",
                 "standardized_stock_exchanges": "xpath",
                 "standardized_directors_officers": "xpath",
                 "standardized_company_ownership_heirarchy": "xpath",
                 "ownership_company_returned": "xpath",
                 "standardized_incorporation_details": "xpath",
                 "matching_scores": "xpath",
                 "watchlist_full_name": "xpath",
                 "is_datasource_called": "xpath",
                 "is_datasource_returned": "xpath",
                 "document_product_requested": "xpath",
                 "document_product_returned": "xpath",
                 "number_of_tradelines": "xpath",
                 "tradeline_summary": "xpath",
                 "dual_process": "xpath",
                 "business_reference_id": "xpath",
                 "telephone": "xpath",
                 "gender": "xpath",
                 "state_province": "xpath"
             }},
            {"name": "United States",
             "form_fields": {
                 "first_name": '//*[@id="FieldSections_0__InputFields_0__StandardInput_Value"]',
                 "first_initial": '//*[@id="FieldSections_0__InputFields_1__StandardInput_Value"]',
                 "middle_name": '//*[@id="FieldSections_0__InputFields_2__StandardInput_Value"]',
                 "middle_initial": '//*[@id="FieldSections_0__InputFields_3__StandardInput_Value"]',
                 "last_name": '//*[@id="FieldSections_0__InputFields_4__StandardInput_Value"]',
                 "date_of_birth_day": '//*[@id="FieldSections_1__InputFields_0__FieldSetInput_Inputs_0__Value"]',
                 "date_of_birth_month": '//*[@id="FieldSections_1__InputFields_0__FieldSetInput_Inputs_1__Value"]',
                 "date_of_birth_year": '//*[@id="FieldSections_1__InputFields_0__FieldSetInput_Inputs_2__Value"]',
                 "address_1": '//*[@id="FieldSections_2__InputFields_0__StandardInput_Value"]',
                 "unit_number": '//*[@id="FieldSections_2__InputFields_1__StandardInput_Value"]',
                 "house_number": '//*[@id="FieldSections_2__InputFields_2__StandardInput_Value"]',
                 "street_name": '//*[@id="FieldSections_2__InputFields_3__StandardInput_Value"]',
                 "street_type": '//*[@id="FieldSections_2__InputFields_4__StandardInput_Value"]',
                 "city": '//*[@id="FieldSections_2__InputFields_5__StandardInput_Value"]',
                 "state": '//*[@id="FieldSections_2__InputFields_6__DropDownInput_Value"]',
                 "postal_code": '//*[@id="FieldSections_2__InputFields_7__StandardInput_Value"]',
                 "driver_licence_number": '//*[@id="FieldSections_3__InputFields_0__StandardInput_Value"]',
                 "driver_licence_state": '//*[@id="FieldSections_3__InputFields_1__StandardInput_Value"]',
                 "social_security_number": '//*[@id="FieldSections_4__InputFields_0__StandardInput_Value"]',
                 "cell_number": '//*[@id="FieldSections_4__InputFields_1__StandardInput_Value"]',
                 "telephone_2": '//*[@id="FieldSections_4__InputFields_2__StandardInput_Value"]',
                 "email_address": '//*[@id="FieldSections_4__InputFields_3__StandardInput_Value"]',
                 "address_association": '//*[@id="FieldSections_4__InputFields_4__StandardInput_Value"]',
                 "field_used": '//*[@id="FieldSections_4__InputFields_5__StandardInput_Value"]',
                 "fraud_flag": '//*[@id="FieldSections_4__InputFields_6__DropDownInput_Value"]',
                 "is_deceased": '//*[@id="FieldSections_4__InputFields_7__DropDownInput_Value"]',
                 "fraud_message": '//*[@id="FieldSections_4__InputFields_8__DropDownInput_Values"]',
                 "phone_type": '//*[@id="FieldSections_4__InputFields_9__StandardInput_Value"]',
                 "risk_level": '//*[@id="FieldSections_4__InputFields_10__StandardInput_Value"]',
                 "risk_description": '//*[@id="FieldSections_4__InputFields_11__StandardInput_Value"]',
                 "mobile_sim_swap_date": '//*[@id="FieldSections_4__InputFields_12__StandardInput_Value"]',
                 "operator": '//*[@id="FieldSections_4__InputFields_13__StandardInput_Value"]',
                 "name_details": '//*[@id="FieldSections_4__InputFields_14__StandardInput_Value"]',
                 "address_details": '//*[@id="FieldSections_4__InputFields_15__StandardInput_Value"]',
                 "phone_details": '//*[@id="FieldSections_4__InputFields_16__StandardInput_Value"]',
                 "person_details": '//*[@id="FieldSections_4__InputFields_17__StandardInput_Value"]',
                 "identification_details": '//*[@id="FieldSections_4__InputFields_18__StandardInput_Value"]',
                 "result_information": '//*[@id="FieldSections_4__InputFields_19__StandardInput_Value"]',
                 "telephone": '//*[@id="FieldSections_4__InputFields_20__StandardInput_Value"]'
             }},
        ]
        target_country = None
        if code_lookup is not False:
            for country in countries_data:
                if country["code"] == country_code:
                    target_country = country
                    break
        else:
            for country in countries_data:
                if country["name"] == country_name:
                    target_country = country
                    break
        field_xpath = target_country["form_fields"]
        return field_xpath
