from typing import Optional

class VirgilKYB:
    def __init__(self, country_name: str, country_code: Optional[str] = None,
                 code_lookup: Optional[bool] = False) -> None:
        self.country_name = country_name
        self.country_code = country_code
        self.code_lookup = code_lookup

    def get_subaccount_entity_form_field_xpath_map(self) -> dict[str, str]:
        country_name = self.country_name
        code_lookup = self.code_lookup
        country_code = self.country_code
        countries_data = [
            {"name": "Australia",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Brazil",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Canada",
             "form_fields": {
                 "business_name": '//*[@id="FieldSections_0__InputFields_0__StandardInput_Value"]',
                 "address_1": '//*[@id="FieldSections_1__InputFields_0__StandardInput_Value"]',
                 "unit_number": '//*[@id="FieldSections_1__InputFields_1__StandardInput_Value"]',
                 "building_number": '//*[@id="FieldSections_1__InputFields_2__StandardInput_Value"]',
                 "house_number": '//*[@id="FieldSections_1__InputFields_3__StandardInput_Value"]',
                 "building_name": '//*[@id="FieldSections_1__InputFields_4__StandardInput_Value"]',
                 "street_name": '//*[@id="FieldSections_1__InputFields_5__StandardInput_Value"]',
                 "street_type": '//*[@id="FieldSections_1__InputFields_6__StandardInput_Value"]',
                 "city": '//*[@id="FieldSections_1__InputFields_7__StandardInput_Value"]',
                 "suburb": '//*[@id="FieldSections_1__InputFields_8__StandardInput_Value"]',
                 "county": '//*[@id="FieldSections_1__InputFields_9__StandardInput_Value"]',
                 "province": '//*[@id="FieldSections_1__InputFields_10__DropDownInput_Value"]',
                 "postal_code": '//*[@id="FieldSections_1__InputFields_11__StandardInput_Value"]',
                 "second_postal_code": '//*[@id="FieldSections_2__InputFields_0__StandardInput_Value"]',
                 "second_state": '//*[@id="FieldSections_2__InputFields_1__StandardInput_Value"]',
                 "second_street_name": '//*[@id="FieldSections_2__InputFields_2__StandardInput_Value"]',
                 "second_street_type": '//*[@id="FieldSections_2__InputFields_3__StandardInput_Value"]',
                 "second_suburb": '//*[@id="FieldSections_2__InputFields_4__StandardInput_Value"]',
                 "second_unit_number": '//*[@id="FieldSections_2__InputFields_5__StandardInput_Value"]',
                 "business_registration_number": '//*[@id="FieldSections_3__InputFields_0__StandardInput_Value"]',
                 "jurisdiction_of_incorporation": '//*[@id="FieldSections_3__InputFields_1__StandardInput_Value"]',
                 "tax_id_number": '//*[@id="FieldSections_3__InputFields_2__StandardInput_Value"]',
                 "second_address_1": '//*[@id="FieldSections_3__InputFields_3__StandardInput_Value"]',
                 "second_city": '//*[@id="FieldSections_3__InputFields_4__StandardInput_Value"]',
                 "second_building_name": '//*[@id="FieldSections_3__InputFields_5__StandardInput_Value"]',
                 "second_building_number": '//*[@id="FieldSections_3__InputFields_6__StandardInput_Value"]',
                 "second_county": '//*[@id="FieldSections_3__InputFields_7__StandardInput_Value"]',
                 "duns_number": '//*[@id="FieldSections_3__InputFields_8__StandardInput_Value"]',
                 "home_jurisdiction": '//*[@id="FieldSections_3__InputFields_9__StandardInput_Value"]',
                 "standardized_registration_numbers": '//*[@id="FieldSections_3__InputFields_10__StandardInput_Value"]',
                 "standardized_metadata": '//*[@id="FieldSections_3__InputFields_11__StandardInput_Value"]',
                 "basic_product_called": '//*[@id="FieldSections_3__InputFields_12__StandardInput_Value"]',
                 "basic_product_returned": '//*[@id="FieldSections_3__InputFields_13__StandardInput_Value"]',
                 "business_status": '//*[@id="FieldSections_3__InputFields_14__StandardInput_Value"]',
                 "datasource_cost": '//*[@id="FieldSections_3__InputFields_15__StandardInput_Value"]',
                 "input_business_name_translated": '//*[@id="FieldSections_3__InputFields_16__StandardInput_Value"]',
                 "input_business_name_transliterated":
                     '//*[@id="FieldSections_3__InputFields_17__StandardInput_Value"]',
                "original_business_status": '//*[@id="FieldSections_3__InputFields_18__StandardInput_Value"]',
                 "returned_business_name_translated": '//*[@id="FieldSections_3__InputFields_19__StandardInput_Value"]',
                 "returned_business_name_transliterated":
                     '//*[@id="FieldSections_3__InputFields_20__StandardInput_Value"]',
                 "standardized_business_names": '//*[@id="FieldSections_3__InputFields_21__StandardInput_Value"]',
                 "api_key_used": '//*[@id="FieldSections_3__InputFields_22__StandardInput_Value"]',
                 "business_legal_form": '//*[@id="FieldSections_3__InputFields_23__StandardInput_Value"]',
                 "enhanced_product_called": '//*[@id="FieldSections_3__InputFields_24__StandardInput_Value"]',
                 "enhanced_product_returned": '//*[@id="FieldSections_3__InputFields_25__StandardInput_Value"]',
                 "entities_product_called": '//*[@id="FieldSections_3__InputFields_26__StandardInput_Value"]',
                 "entities_product_returned": '//*[@id="FieldSections_3__InputFields_27__StandardInput_Value"]',
                 "standardized_locations": '//*[@id="FieldSections_3__InputFields_28__StandardInput_Value"]',
                 "vendor_transactional_references": '//*[@id="FieldSections_3__InputFields_29__StandardInput_Value"]',
                 "warning": '//*[@id="FieldSections_3__InputFields_30__StandardInput_Value"]',
                 "matching_scores": '//*[@id="FieldSections_3__InputFields_31__StandardInput_Value"]',
                 "respect_enhanced": '//*[@id="FieldSections_3__InputFields_32__StandardInput_Value"]',
                 "standardized_communication": '//*[@id="FieldSections_3__InputFields_33__StandardInput_Value"]',
                 "province_code": '//*[@id="FieldSections_3__InputFields_34__StandardInput_Value"]',
                 "state_province": '//*[@id="FieldSections_3__InputFields_35__StandardInput_Value"]'
             }},
            {"name": "China",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Hong Kong",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "New Zealand",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Italy",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Ireland",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Japan",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Nigeria",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "Taiwan",
             "form_fields": {
                 "first_name": "xpath",
                 "last_name": "xpath",
                 "country": "xpath",
             }},
            {"name": "United Kingdom",
             "form_fields": {
                 "first_name": "xpath",
                 "first_initial": "xpath",
                 "middle_name": "xpath",
                 "middle_initial": "xpath",
                 "last_name": "xpath",
                 "business_name": "xpath",
                 "tradestyle_name": "xpath",
                 "date_of_birth_day": "xpath",
                 "date_of_birth_month": "xpath",
                 "date_of_birth_year": "xpath",
                 "address_1": "xpath",
                 "unit_number": "xpath",
                 "building_number": "xpath",
                 "house_number": "xpath",
                 "building_name": "xpath",
                 "street_name": "xpath",
                 "street_type": "xpath",
                 "city": "xpath",
                 "suburb": "xpath",
                 "county": "xpath",
                 "state": "xpath",
                 "postal_code": "xpath",
                 "second_unit_number": "xpath",
                 "second_street_name": "xpath",
                 "second_street_type": "xpath",
                 "second_suburb": "xpath",
                 "second_postal_code": "xpath",
                 "second_state": "xpath",
                 "business_registration_number": "xpath",
                 "cell_number": "xpath",
                 "email_address": "xpath",
                 "telephone_2": "xpath",
                 "jurisdiction_of_incorporation": "xpath",
                 "duns_number": "xpath",
                 "second_address_1": "xpath",
                 "second_city": "xpath",
                 "second_building_name": "xpath",
                 "second_building_number": "xpath",
                 "tax_id_number": "xpath",
                 "enhanced_profile": "xpath",
                 "business_risk_valies": "xpath",
                 "entities": "xpath",
                 "second_county": "xpath",
                 "people_of_significant_control": "xpath",
                 "annual_accounts": "xpath",
                 "article_of_association": "xpath",
                 "annual_report": "xpath",
                 "capital_document": "xpath",
                 "liquidation_document": "xpath",
                 "mortgage_document": "xpath",
                 "watchlist_data": "xpath",
                 "watchlist_state": "xpath",
                 "watchlist_hit_details": "xpath",
                 "is_decesased": "xpath",
                 "field_used": "xpath",
                 "address_association": "xpath",
                 "phone_type": "xpath",
                 "risk_level": "xpath",
                 "risk_description": "xpath",
                 "mobile_sim_swap_date": "xpath",
                 "operator": "xpath",
                 "business_status": "xpath",
                 "original_business_status": "xpath",
                 "standardized_registration_numbers": "xpath",
                 "standardized_locations": "xpath",
                 "standardized_metadata": "xpath",
                 "basic_product_called": "xpath",
                 "basic_product_returned": "xpath",
                 "enhanced_product_called": "xpath",
                 "enhanced_product_returned": "xpath",
                 "input_business_name_translated": "xpath",
                 "returned_business_name_translated": "xpath",
                 "returned_business_name_transliterated": "xpath",
                 "entities_product_called": "xpath",
                 "entities_product_returned": "xpath",
                 "warning": "xpath",
                 "standardized_business_names": "xpath",
                 "respect_enhanced": "xpath",
                 "business_status_details": "xpath",
                 "standardized_communication": "xpath",
                 "vendor_transactional_references": "xpath",
                 "business_legal_form": "xpath",
                 "original_business_legal_form": "xpath",
                 "year_of_incorporation": "xpath",
                 "month_of_incorporation": "xpath",
                 "day_of_incorporation": "xpath",
                 "standardized_share_capitals": "xpath",
                 "standardized_industries": "xpath",
                 "standardized_stock_exchanges": "xpath",
                 "standardized_directors_officers": "xpath",
                 "standardized_company_ownership_heirarchy": "xpath",
                 "ownership_company_returned": "xpath",
                 "standardized_incorporation_details": "xpath",
                 "matching_scores": "xpath",
                 "watchlist_full_name": "xpath",
                 "is_datasource_called": "xpath",
                 "is_datasource_returned": "xpath",
                 "document_product_requested": "xpath",
                 "document_product_returned": "xpath",
                 "number_of_tradelines": "xpath",
                 "tradeline_summary": "xpath",
                 "dual_process": "xpath",
                 "business_reference_id": "xpath",
                 "telephone": "xpath",
                 "gender": "xpath",
                 "state_province": "xpath"
             }},
            {"name": "United States",
             "form_fields": {
                 "business_name": '//*[@id="FieldSections_0__InputFields_0__StandardInput_Value"]',
                 "address_1": '//*[@id="FieldSections_1__InputFields_0__StandardInput_Value"]',
                 "unit_number": '//*[@id="FieldSections_1__InputFields_1__StandardInput_Value"]',
                 "building_number": '//*[@id="FieldSections_1__InputFields_2__StandardInput_Value"]',
                 "building_name": '//*[@id="FieldSections_1__InputFields_3__StandardInput_Value"]',
                 "street_name": '//*[@id="FieldSections_1__InputFields_4__StandardInput_Value"]',
                 "street_type": '//*[@id="FieldSections_1__InputFields_5__StandardInput_Value"]',
                 "city": '//*[@id="FieldSections_1__InputFields_6__StandardInput_Value"]',
                 "suburb": '//*[@id="FieldSections_1__InputFields_7__StandardInput_Value"]',
                 "county": '//*[@id="FieldSections_1__InputFields_8__StandardInput_Value"]',
                 "postal_code": '//*[@id="FieldSections_1__InputFields_9__StandardInput_Value"]',
                 "second_unit_number": '//*[@id="FieldSections_2__InputFields_0__StandardInput_Value"]',
                 "second_street_name": '//*[@id="FieldSections_2__InputFields_1__StandardInput_Value"]',
                 "second_street_type": '//*[@id="FieldSections_2__InputFields_2__StandardInput_Value"]',
                 "second_suburb": '//*[@id="FieldSections_2__InputFields_3__StandardInput_Value"]',
                 "second_postal_code": '//*[@id="FieldSections_2__InputFields_4__StandardInput_Value"]',
                 "second_state": '//*[@id="FieldSections_2__InputFields_5__StandardInput_Value"]',
                 "tax_id_number": '//*[@id="FieldSections_3__InputFields_0__StandardInput_Value"]',
                 "jurisdiction_of_incorporation": '//*[@id="FieldSections_3__InputFields_1__StandardInput_Value"]',
                 "business_registration_number": '//*[@id="FieldSections_3__InputFields_2__StandardInput_Value"]',
                 "duns_number": '//*[@id="FieldSections_3__InputFields_3__StandardInput_Value"]',
                 "second_address_1": '//*[@id="FieldSections_3__InputFields_4__StandardInput_Value"]',
                 "second_city": '//*[@id="FieldSections_3__InputFields_5__StandardInput_Value"]',
                 "second_building_name": '//*[@id="FieldSections_3__InputFields_6__StandardInput_Value"]',
                 "second_building_number": '//*[@id="FieldSections_3__InputFields_7__StandardInput_Value"]',
                 "second_county": '//*[@id="FieldSections_3__InputFields_8__StandardInput_Value"]',
                 "business_status": '//*[@id="FieldSections_3__InputFields_9__StandardInput_Value"]',
                 "original_business_status": '//*[@id="FieldSections_3__InputFields_10__StandardInput_Value"]',
                 "standardized_registration_numbers": '//*[@id="FieldSections_3__InputFields_11__StandardInput_Value"]',
                 "standardized_locations": '//*[@id="FieldSections_3__InputFields_12__StandardInput_Value"]',
                 "standardized_metadata": '//*[@id="FieldSections_3__InputFields_13__StandardInput_Value"]',
                 "basic_product_called": '//*[@id="FieldSections_3__InputFields_14__StandardInput_Value"]',
                 "basic_product_returned": '//*[@id="FieldSections_3__InputFields_15__StandardInput_Value"]',
                 "enhanced_product_called": '//*[@id="FieldSections_3__InputFields_16__StandardInput_Value"]',
                 "enhanced_product_returned": '//*[@id="FieldSections_3__InputFields_17__StandardInput_Value"]',
                 "input_business_name_translated": '//*[@id="FieldSections_3__InputFields_18__StandardInput_Value"]',
                 "input_business_name_transliterated": '//*[@id="FieldSections_3__InputFields_19__StandardInput_Value"]',
                 "returned_business_name_translated": '//*[@id="FieldSections_3__InputFields_20__StandardInput_Value"]',
                 "returned_business_name_transliterated":
                     '//*[@id="FieldSections_3__InputFields_21__StandardInput_Value"]',
                 "entities_product_called": '//*[@id="FieldSections_3__InputFields_22__StandardInput_Value"]',
                 "entities_product_returned": '//*[@id="FieldSections_3__InputFields_23__StandardInput_Value"]',
                 "warning": '//*[@id="FieldSections_3__InputFields_24__StandardInput_Value"]',
                 "standardized_business_names": '//*[@id="FieldSections_3__InputFields_25__StandardInput_Value"]',
                 "standardized_communication": '//*[@id="FieldSections_3__InputFields_26__StandardInput_Value"]',
                 "respect_enhanced": '//*[@id="FieldSections_3__InputFields_27__StandardInput_Value"]',
                 "vendor_transactional_references": '//*[@id="FieldSections_3__InputFields_28__StandardInput_Value"]',
                 "business_reference_id": '//*[@id="FieldSections_3__InputFields_29__StandardInput_Value"]',
                 "matching_scores": '//*[@id="FieldSections_3__InputFields_30__StandardInput_Value"]',
                 "state_province": '//*[@id="FieldSections_3__InputFields_31__StandardInput_Value"]'
             }},
        ]
        target_country = None
        if code_lookup is not False:
            for country in countries_data:
                if country["code"] == country_code:
                    target_country = country
                    break
        else:
            for country in countries_data:
                if country["name"] == country_name:
                    target_country = country
                    break
        field_xpath = target_country["form_fields"]
        return field_xpath

